name: hasql-queue
version: '1.0.0.1'
synopsis: A PostgreSQL backed queue
description: A PostgreSQL backed queue. Please see README.md
category: Web
author: Jonathan Fischoff
maintainer: jonathangfischoff@gmail.com
copyright: 2020 Jonathan Fischoff
license: BSD3
github: jfischoff/hasql-queue
extra-source-files:
- README.md
ghc-options:
- -Wall
- -Wno-unused-do-bind
- -Wno-unused-foralls
extra-source-files:
 - README.md
 - CHANGELOG.md


tested-with: GHC ==8.8.1

default-extensions:
- OverloadedStrings
- LambdaCase
- RecordWildCards
- TupleSections
- GeneralizedNewtypeDeriving
- QuasiQuotes
- ScopedTypeVariables
- TypeApplications
- AllowAmbiguousTypes

dependencies:
- base >=4.7 && <5
- time
- transformers
- random
- text
- monad-control
- exceptions
- hasql
- postgresql-libpq
- postgresql-libpq-notify >= 0.2.0.0
- aeson
- bytestring
- stm
- here

library:
  source-dirs: src

tests:
  unit-tests:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base64-bytestring
    - cryptohash-sha1
    - hasql-queue
    - hspec
    - hspec-core
    - hspec-expectations-lifted
    - async
    - split
    - tmp-postgres
    - resource-pool

executables:
  benchmark:
    main: Main.hs
    source-dirs: benchmarks
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -g2
    dependencies:
      - base64-bytestring
      - cryptohash-sha1
      - hasql-queue
      - async
      - tmp-postgres
      - resource-pool
